apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: serf-publisher
  labels:
    app: serf-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serf-publisher
  template:
    metadata:
      labels:
        app: serf-publisher
    spec:
      containers:
        - name: serf-publisher
          image: ismaelfm/serf-publisher:0.1.0
          env:
          - name: NAMESPACE
            value: default 
