kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: cloudy
  name: ismael-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ismael-rolebinding
  namespace: cloudy
subjects:
- kind: User
  name: ismael
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ismael-role
  apiGroup: rbac.authorization.k8s.io
