kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: cloudy
  name: pod-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-pods
  namespace: cloudy
subjects:
- kind: ServiceAccount
  name: default
  namespace: cloudy
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
